### ISSUE TITLE
Bug: Recent commits broke Re::Solve examples

### ISSUE THREAD

**Issue by pelesh** [ORNL/ReSolve#444]
### Description how to reproduce the bug

 Re::Solve examples seem to be broken. For example, running `gluRefactor` gives following error messages:
```
$ ./gluRefactor.exe -m ../../activsg10k/matrix_ACTIVSg10k_AC_ -r ../../activsg10k/rhs_ACTIVSg10k_AC_ -e mm -n 20
Family mtx file name: ../../activsg10k/matrix_ACTIVSg10k_AC_, total number of matrices: 20
Family rhs file name: ../../activsg10k/rhs_ACTIVSg10k_AC_, total number of RHSes: 20
gluRefactor with CUDA backend
System 1:

========================================================================================================================
Reading: ../../activsg10k/matrix_ACTIVSg10k_AC_01.mm
========================================================================================================================

Finished reading the matrix and rhs, size: 238072 x 238072, nnz: 1209368, symmetric? 1, Expanded? 1
CSR matrix loaded. Expanded NNZ: 1209368
KLU analysis status: 0
KLU factorization status: 0
KLU solve status: 0
Refactorization setup status: 0
[ERROR] Trying to copy from external vector, but destination (device) is not allocated!
[ERROR] Dot product failed with error code 15
[ERROR] CUDA error in function cudaMalloc((void**) v, sizeof(T) * n) at /home/55y/src/resolve/ReSolve/resolve/cuda/CudaMemory.hpp:60, error# 700
[ERROR] CUDA error in function cudaMalloc((void**) v, sizeof(T) * n) at /home/55y/src/resolve/ReSolve/resolve/cuda/CudaMemory.hpp:60, error# 700
[WARNING] Vector inf nrm returned 6
[ERROR] cusolverSpDnrminf failed with error code 6
[ERROR] cusolverSpDnrminf failed with error code 6
         2-Norm of the residual (before IR): 0.0000000000000000e+00
         Matrix inf  norm: 0.0000000000000000e+00
         Residual inf norm: 0.0000000000000000e+00
         Solution inf norm: 0.0000000000000000e+00
         Norm of scaled residuals: -nan
```

### Re::Solve version

develop at a93fb6571e3542b2fa779983fef0186a034c53c9

### System and environment details

```
$ uname -a
Linux pdesx 5.15.0-177-generic #187-Ubuntu

gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0
```

### Additional information

CC @shakedregev

**Comment by shakedregev** [comment]
I can't run anything on the pdesx machine, so that may be the problem.

**Comment by andrewxu319** [comment]
> I can't run anything on the pdesx machine, so that may be the problem.

I can't either. Is someone using it?

**Comment by tamar-dewilde** [comment]
I reproduced the bug locally with the same command and ACTIVSg10k dataset:

```console
$ ./gluRefactor.exe -m ../../activsg10k/matrix_ACTIVSg10k_AC_ -r ../../activsg10k/rhs_ACTIVSg10k_AC_ -e mm -n 20
Family mtx file name: ../../activsg10k/matrix_ACTIVSg10k_AC_, total number of matrices: 20
Family rhs file name: ../../activsg10k/rhs_ACTIVSg10k_AC_, total number of RHSes: 20
gluRefactor with CUDA backend
System 1:

========================================================================================================================
Reading: ../../activsg10k/matrix_ACTIVSg10k_AC_01.mm
========================================================================================================================

Finished reading the matrix and rhs, size: 238072 x 238072, nnz: 1209368, symmetric? 1, Expanded? 1
CSR matrix loaded. Expanded NNZ: 1209368
KLU analysis status: 0
KLU factorization status: 0
KLU solve status: 0
Refactorization setup status: 0
[ERROR] Trying to copy from external vector, but destination (device) is not allocated!
[ERROR] Dot product failed with error code 15
[ERROR] CUDA error in function cudaMalloc((void**) v, sizeof(T) * n) at /home/tdewilde/ReSolve-issue444/resolve/cuda/CudaMemory.hpp:60, error# 700
[ERROR] CUDA error in function cudaMalloc((void**) v, sizeof(T) * n) at /home/tdewilde/ReSolve-issue444/resolve/cuda/CudaMemory.hpp:60, error# 700
[WARNING] Vector inf nrm returned 6
[ERROR] cusolverSpDnrminf failed with error code 6
[ERROR] cusolverSpDnrminf failed with error code 6
         2-Norm of the residual (before IR): 0.0000000000000000e+00
         Matrix inf  norm: 0.0000000000000000e+00
         Residual inf norm: 0.0000000000000000e+00
         Solution inf norm: 0.0000000000000000e+00
         Norm of scaled residuals: -nan
```

The same errors continue for all 20 systems. `gluRefactor.exe` returns exit code 0.

The registered GLU tests pass:

```console
klu_glu_cuda_test   Passed
sys_glu_test        Passed
sys_glu_asym_test   Passed

100% tests passed, 0 tests failed out of 3
Total Test time (real) = 1.94 sec
```

The complete test suite also passes:

```console
100% tests passed, 0 tests failed out of 67
Total Test time (real) = 43.93 sec
```

### Re::Solve version

`develop` at `bd60de0`

### System and environment details

```console
$ uname -a
Linux TamarROG 6.18.33.2-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Thu Jun 18 21:54:43 UTC 2026 x86_64 x86_64 x86_64 GNU/Linux

$ gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0

GPU: NVIDIA GeForce RTX 2060 with Max-Q Design
Driver: 572.42
```

**Comment by tamar-dewilde** [comment]
@shakedregev I ran `git bisect` and found that the first bad commit is [`a93fb65`](https://github.com/ORNL/ReSolve/commit/a93fb6571e3542b2fa779983fef0186a034c53c9), from [#436](https://github.com/ORNL/ReSolve/pull/436). Its parent, [`f79151e`](https://github.com/ORNL/ReSolve/commit/f79151e023be90061725458561a3cf1f138da728), does not produce the system 1 allocation/CUDA 700 failure.

I found two missing updates:

- `ExampleHelper::printSummary()` creates `res_` without allocating it.
- `gluRefactor.cpp` allocates the reused matrix and RHS device storage on every iteration instead of only once.

I tested a small fix on [`bd60de0`](https://github.com/ORNL/ReSolve/commit/bd60de098b46e835cf8ae2339f15149cf25ea5b2) that allocates `res_` when it is created and allocates the matrix/RHS device storage only for the first system.

After the fix:

- The 20-system ACTIVSg10k run has no memory-management or CUDA errors.
- The GLU tests pass 3/3.
- The full test suite passes 67/67.

Systems 12 and 13 still produce NaNs, but the same systems also produce NaNs on the parent commit, so this appears to be a separate issue.

Happy to open a PR with this fix if useful.

**Comment by shakedregev** [comment]
Great work, yes please open the PR. Systems 12 and 13 have a different sparsity structure I believe. So this is a failure we expect.
